/*
* Weather station code
* - Requires: 
* -- RF24: https://github.com/tmrh20/RF24/
* -- dht: http://playground.arduino.cc/Main/DHTLib
* -- SFE_BMP180: https://github.com/sparkfun/BMP180_Breakout_Arduino_Library/archive/master.zip
* - Pins will be added, eventually
*
* - use writeToMessage() to add text to the message
* - use sendMessage() to transmit your message. Note that this clears the message buffer!
* -- Also, a checksum is generated by adding the ASCII values of each character in the message, cleared on send as well
* - doubleToString() for convenience
*/
#include <string.h>
#include <SPI.h>
#include <nRF24L01.h> //wireless
#include <RF24.h> //wireless
#include <SFE_BMP180.h> //to read pressure
#include <dht.h> //for the temperature

#define DHT11_PIN 8
#define DECIMAL_STR_LENGTH 11 //Increase this for more sigfigs, floors to hundredth place
#define TEXT_MAX_LENGTH 100

RF24 radio(9, 10); // CE, CSN
SFE_BMP180 pressure;
dht DHT;

const byte address[6] = "00001";
char decimalAsString[DECIMAL_STR_LENGTH]; //buffer to store return from doubleToString

char *doubleToString(double d);
void writeToMessage(char *text);
void sendMessage();

struct message{
  char text[TEXT_MAX_LENGTH];
  char *curs0r = text;
  int checksum;
}transMsg; //Message object

void setup() {
  Serial.begin(9600);
  //Init radio
  radio.begin();
  radio.openWritingPipe(address);
  radio.setPALevel(RF24_PA_MIN);
  radio.stopListening();
  //Check i2c on BMP sensor
  if(pressure.begin() == 0)
    Serial.println("Error initializing BMP");
}

void loop() {
  char stat;
  double T,P;
  short transmit_period = 2000;
  int chk = DHT.read11(DHT11_PIN);//get values from dht

  //Get temp for pressure reading
  stat = pressure.startTemperature();
  if(stat != 0)
    delay(stat);
  stat = pressure.getTemperature(T);
  //If stat is 0, there is an i2c error
  if(stat == 0){
    Serial.println("BMP: Temperature Error (I2C)");
    T = -273.15;
  }
  stat = pressure.startPressure(3);
  if(stat != 0)
    delay(stat);
  if(T != -273.15){
    stat = pressure.getPressure(P,T);
    //If stat is 0, there is an i2c error
    if(stat == 0){
      Serial.println("BMP: Pressure Error (I2C)");
      P = 0;
    }
  }
  writeToMessage("Air:");
  writeToMessage(doubleToString(analogRead(A0)));
  
  writeToMessage(" Soil:");
  writeToMessage(doubleToString(analogRead(A1)));

  writeToMessage(" BMPPres:");
  writeToMessage(doubleToString(P));

  writeToMessage(" BMPTemp:");
  writeToMessage(doubleToString(T));

  //Read values from dht
  writeToMessage(" Hum:");
  writeToMessage(doubleToString(DHT.humidity));
  writeToMessage(" Temp:");
  writeToMessage(doubleToString(DHT.temperature));
  //print for debugging
  Serial.println(transMsg.text);
  //Send data and clear buffer
  sendMessage();
  delay(transmit_period);
}

//Convert double to string
char *doubleToString(double d){
  int prefix, postfix;
  char pre[DECIMAL_STR_LENGTH - 3], post[2];
  char decimal = '.';

  //Get the digits before the decimal
  prefix = (int)d;
  //Get the digits 2 places after the decimal
  postfix = abs((int)(100*(d - (double)prefix)));
  //Make prefix a String in base 10
  itoa(prefix, pre, 10);
  //Make postfix a String in base 10
  itoa(postfix, post, 10);
  //Put it all together
  strcpy(decimalAsString,pre);
  strcat(decimalAsString,".");
  strcat(decimalAsString,post);
  //returning the char pointer makes the code cleaner
  return decimalAsString;
}

//Write message to our buffer
void writeToMessage(char *text){
  int len = strlen(text);
  strcpy(transMsg.curs0r,text);
  transMsg.curs0r += len;
}

//Send message over radio
void sendMessage(){
  //generate checksum
  for(int i = 0; i < TEXT_MAX_LENGTH; i++){
    transMsg.checksum += (short)transMsg.text[i];
  }
  //Send the message
  radio.write(&transMsg, sizeof(transMsg));
  //Reset message
  memset(transMsg.text, 0, TEXT_MAX_LENGTH);
  transMsg.curs0r = transMsg.text;
  transMsg.checksum = 0;
}

//ya boy
